[package]
name = "jun3"
version = "0.1.0"
edition = "2021"

[dependencies]
derivative = "2.2.0"
kdam = "0.5.2"
lazy_static = "1.5.0"

# Run tests with opt level 3
#[profile.dev]
#opt-level = 1

[profile.test]
# Opt 1
opt-level = 1
## Keep debug info
#debug = "full"

