[package]
name = "jun3"
version = "0.1.0"
edition = "2021"

[dependencies]
kdam = "0.5.2"
unicode-general-category = "0.6.0"
unicode-segmentation = "1.11.0"

# Run tests with opt level 3
#[profile.dev]
#opt-level = 1

[profile.test]
opt-level = 1
