[package]
name = "_glrmask"
version = "0.1.1"
edition = "2021"

[lib]
name = "_glrmask"
crate-type = ["cdylib"]
doc = false


[features]
default = []
allocation-tracking = []

[dependencies]
pyo3 = { version = "0.24.2", features = ["extension-module"] }
numpy = "0.24.0"
glrmask = { path = "..", features = ["internal-api"] }
self_cell = "1"
mimalloc = "=0.1.52"
libmimalloc-sys = { version = "=0.1.49", default-features = false, features = ["extended"] }
serde_json = { version = "1", features = ["preserve_order"] }
